### ISSUE TITLE
could figures library be used on python 3.8.5?

### ISSUE THREAD

**Issue by ardeal** [appsembler/figures#319] opened 2021-01-12 05:05 UTC
Hi,

I am using python 3.8.5.

In my code, the following code will encountered the following issue:

<code> from figures import set_limits, plot_coords, plot_bounds, plot_line_issimple </code>

```Python
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/doc/code_python/har/annotation/linestring.py", line 4, in <module>
    from figures import set_limits, plot_coords, plot_bounds, plot_line_issimple
ImportError: cannot import name 'set_limits' from 'figures' (C:\ProgramData\Anaconda3\lib\site-packages\figures\__init__.py)

```

**Comment by johnbaldwin** [comment] 2021-02-17 16:44
Closing as this is a duplicate of https://github.com/appsembler/figures/issues/318

**Closed by johnbaldwin** 2021-02-17 16:44 UTC
